apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  database_url: jdbc:mysql://mysql-service:3306/k8s-tutorial?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true