apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql # This is the label of the deployment, it is used by the service.
spec:
  replicas: 1
  selector:
    matchLabels: # This tells which pods belong to the deployment
      app: mysql
  template:
    metadata:
      labels:
        app: mysql # This is matched by matchLabels to register this pod with the deployment.
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306